MadSwag
=======

This repo contains the code for my sports pool web application at MadSwag.com, including templates for building new games. The front-end is built using XHMTL, CSS, and jQuery, and is generated by custom PHP functions. The back-end is built using PHP and MySQL, and is intended to be used with an Apache server.
